# Generated by Django 2.0.3 on 2018-04-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyokigo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyokigo_input',
            name='ownurl',
        ),
        migrations.AlterField(
            model_name='kyokigo_input',
            name='text',
            field=models.CharField(max_length=100, verbose_name='テキスト'),
        ),
    ]
