# Generated by Django 2.0.3 on 2018-05-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ownurl',
            field=models.URLField(default='URLを入力して下さい', verbose_name='URL'),
        ),
    ]
