# Generated by Django 2.0.3 on 2018-05-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_post_ownurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ownurl',
            new_name='url',
        ),
    ]
