# Generated by Django 2.0.3 on 2018-05-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='r_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='jfile',
            field=models.FileField(default='graph.json', upload_to=''),
        ),
    ]
